---
title: "lihc_tcga_0.R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
source("function_heatmap_cluster_combn_after_jianjun.R")
EDA=function(x){
  windows()
  par(mfrow=c(3,2))
  hist(x)
  dotchart(x)
  boxplot(x,horizontal = T)
  qqnorm(x);qqline(x)
  mtext("title",outer = TRUE)
  par(mfrow=c(1,1))
}
##定义参数列表
para_List=c()
#title0="t_cell_signature"
title0="PTEN_signature"
getGene0="ALL";
k_n0=3

##读取数据ran_seq_median
path="D:\\min数据\\tcga\\lihc_tcga\\lihc_tcga\\"
out_put_dir=paste(path,getGene0,"\\",sep="")
label_Func_readInRnaSeqFile=function(){print("读入RNAseq表达数据！")}
file=paste(path,list.files(path = path,pattern = "data.*?RNA_Seq.*?expression.*?median.*?txt"),sep="")
#file=paste(path,list.files(path = path,pattern = "data.*?RNA_Seq.*?Zscores.*?txt"),sep="")

RDSfile=sub(pattern = "txt",replacement = "RDS",perl=TRUE,x=file)
useSymbol = TRUE
library(data.table)
#file=paste(path,"data_RNA_Seq_v2_mRNA_median_Zscores.RDS",sep="")
if(file.exists(RDSfile)){
  rna_seq_data=readRDS(file=RDSfile)
}else{
  rna_data=read.csv(file = file,sep = "\t")
  saveRDS(rna_data,file=RDSfile)
  rna_seq_data=readRDS(file=RDSfile)
}
if(data.class(rna_seq_data)!="data.table"){
  rna_seq_data=data.table(rna_seq_data)
}

##rnaSEQ文件探针合并.max,average??
##这里我们使用data.table的.SD方法
receive=winDialogString(as.character(nrow(rna_seq_data)!=length(unique(rna_seq_data$Hugo_Symbol))),default = "发现重复基因名称")
rna_seq_data=rna_seq_data[,lapply(.SD,max),by=.(Hugo_Symbol),.SDcols=colnames(rna_seq_data)[c(2:ncol(rna_seq_data))]]
rna_seq_data=na.omit(as.data.frame(rna_seq_data))
rownames(rna_seq_data)=rna_seq_data$Hugo_Symbol
##选取基因
PTEN_geneSignatures=c("BZS","SLC30A1")##BZS=PTEN,
geneSignatures=PTEN_geneSignatures
#fix(rna_seq_data)
head(rna_seq_data,1)


ifelse(useSymbol,{
  rna_seq_data=na.omit(rna_seq_data)
  rownames(rna_seq_data)<-rna_seq_data$Hugo_Symbol;
  "基因symbol应用完毕"
},{
  rownames(rna_seq_data)=rna_seq_data$Entrez_Gene_Id;
  "基因ID应用完毕"
})

##开始获取signature基因
data_signatire=rna_seq_data[geneSignatures,]

tryCatch({
  if("Entrez_Gene_Id" %in% colnames(data_signatire)){
    data_signatire=data_signatire[,-which(colnames(data_signatire)=="Entrez_Gene_Id")]  
  }
  if("Hugo_Symbol" %in% colnames(data_signatire)){
    data_signatire=data_signatire[,-which(colnames(data_signatire)=="Hugo_Symbol")]
  }
},finally = {
  "全部去除完毕!"
  #  write.csv(x=data_signatire,file = paste(out_put_dir,"tcga_signature.csv",sep=""))
})


tryCatch({
  if("Entrez_Gene_Id" %in% colnames(rna_seq_data)){
    rna_seq_data=rna_seq_data[,-which(colnames(rna_seq_data)=="Entrez_Gene_Id")]  
  }
  if("Hugo_Symbol" %in% colnames(rna_seq_data)){
    rna_seq_data=rna_seq_data[,-which(colnames(rna_seq_data)=="Hugo_Symbol")]
  }
},finally = {
  "全部去除完毕!"
  #  write.csv(x=data_signatire,file = paste(out_put_dir,"tcga_signature.csv",sep=""))
})


##查看未找到的名称
rownames(data_signatire)=geneSignatures
#write.csv(x=t(data_signatire),file = paste("D:\\min数据\\tcga\\prad_tcga\\analyse\\spss\\log2.csv",sep=""))
#shell.exec("D:\\min数据\\tcga\\prad_tcga\\analyse\\spss\\")
fix(data_signatire)
print(summary(is.na(rownames(data_signatire))))

##非常必要加载高性能的包
library(matrixStats)
library(NMF)
if(TRUE){
  {"是否进行log2处理"}
  secondMin=min(as.matrix(data_signatire)[which(data_signatire!=0)])
  #print(secondMin)
  data_signatire=log2(data_signatire+1)  
  # write.csv(x=t(data_signatire),file = paste("D:\\min数据\\tcga\\prad_tcga\\analyse\\spss\\log2_true.csv",sep=""))
  #shell.exec("D:\\min数据\\tcga\\prad_tcga\\analyse\\spss\\")
  para_List[length(para_List)+1]="log2"
}
#!!!查看每个基因的数值分布
library(ggplot2)
library(lattice)
par(mfrow=c(2,1));
apply(data_signatire,MARGIN = 1, function(x){
win.graph();a=densityplot(unlist(x));print(a);
print(mean(unlist(x)))
})
par(mfrow=c(1,1))
if(TRUE){
  data_signatire=as.data.frame(t(scale(t(data_signatire))))
  para_List[length(para_List)+1]="rowWiseScale"
}
apply(data_signatire,MARGIN = 1, function(x){
  win.graph();a=densityplot(unlist(x));print(a);
  print(mean(unlist(x)))
})
if(FALSE){
  ###rowMeans进行中心化
  data_signatire=data_signatire-rowMedians(as.matrix(data_signatire))
  para_List[length(para_List)+1]="rowMeansCenteralized"
}

library(lattice)
curve=densityplot(unlist(data_signatire));win.graph();print(curve);
fix(data_signatire)
for(rowIndex in c(1:nrow(data_signatire))){
  data_signatire[rowIndex,]
  #win.graph();print(densityplot(unlist(data_signatire[rowIndex,])));
}

if(FALSE){
  {"确定最佳的聚类数目"}
  library(mclust)
  m_clust=mclust()
}

library(factoextra)
library(cluster)

label_Func_OutputDir=function(){print("打开输出文件文件夹！")}
if(!dir.exists(paste(out_put_dir,title0,paste(para_List,collapse = "_"),"r_heriachical\\",k_n0,"\\",sep=""))){
  dir.create(recursive=TRUE,paste(out_put_dir,title0,paste(para_List,collapse = "_"),"r_heriachical\\",k_n0,"\\",sep=""))
}
out_put_dir=paste(out_put_dir,title0,paste(para_List,collapse = "_"),"r_heriachical\\",k_n0,"\\",sep="")
shell.exec(path)
shell.exec(paste(out_put_dir,sep=""))
fix(data_signatire)
#######相关系数计算
data2cor=t(rna_seq_data)
##去除标准差为0的变量
data2cor=data2cor[,which(colSds(data2cor)!=0)]
colSds(data2cor[,geneSignatures])==0
r_cor=cor(data2cor[,geneSignatures],data2cor)
t_r_cor=t(r_cor)
fix(r_cor);win.graph();plot(t(r_cor));
library(ggplotgui)
library(dplyr)
ggplot_shiny(tbl_df(t_r_cor))
##计算带P的相关系数
library(ppcor)
p_cor=pcor.test(data2cor[,1],data2cor[,geneSignatures])

```


```{python python, echo=TRUE}






```